id: P010364
initial_creation_type: ocr
source_metadata:
  id: bdr:W29564
  title: གསུང་འབུམ། ཡོན་ཏན་མགོན་པོ
  author: ''
  volumes:
    56f4b047861742708fb49fcc20d26bdc:
      image_group_id: I6015
      title: ''
      volume_number: 1
      total_pages: 459
      base_file: v001.txt
